// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System.Collections.Generic;

using Kentico.Kontent.Delivery.Abstractions;

namespace KenticoKontentBlog.Feature.Kontent.Models
{
    public partial class AuthorPage
    {
        public const string Codename = "author_page";
        public const string BiographyCodename = "biography";
        public const string FacebookUserNameCodename = "facebook_user_name";
        public const string HeroHeaderCodename = "hero__header";
        public const string HeroHeaderImageCodename = "hero__header_image";
        public const string HeroHeaderImageHorizontalAlignmentCodename = "hero__header_image_horizontal_alignment";
        public const string HeroHeaderImageVerticalAlignmentCodename = "hero__header_image_vertical_alignment";
        public const string NameCodename = "name";
        public const string ProfileImageCodename = "profile_image";
        public const string SeoMetaDataMetaDescriptionCodename = "seo_meta_data__meta_description";
        public const string SeoMetaDataMetaImagesCodename = "seo_meta_data__meta_images";
        public const string SeoMetaDataMetaTitleCodename = "seo_meta_data__meta_title";
        public const string SeoMetaDataTwitterAccountCodename = "seo_meta_data__twitter_account";
        public const string TwitterAccountCodename = "twitter_account";

        public IRichTextContent Biography { get; set; }
        public string FacebookUserName { get; set; }
        public string HeroHeader { get; set; }
        public IEnumerable<IAsset> HeroHeaderImage { get; set; }
        public IEnumerable<IMultipleChoiceOption> HeroHeaderImageHorizontalAlignment { get; set; }
        public IEnumerable<IMultipleChoiceOption> HeroHeaderImageVerticalAlignment { get; set; }
        public string Name { get; set; }
        public IEnumerable<IAsset> ProfileImage { get; set; }
        public string SeoMetaDataMetaDescription { get; set; }
        public IEnumerable<IAsset> SeoMetaDataMetaImages { get; set; }
        public string SeoMetaDataMetaTitle { get; set; }
        public IEnumerable<IMultipleChoiceOption> SeoMetaDataTwitterAccount { get; set; }
        public IContentItemSystemAttributes System { get; set; }
        public string TwitterAccount { get; set; }
    }
}