// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace KenticoKontentBlog.Feature.Kontent.Models
{
    public partial class HtmlSiteMapPage
    {
        public const string Codename = "html_site_map_page";
        public const string HeroHeaderCodename = "hero__header";
        public const string HeroHeaderImageCodename = "hero__header_image";
        public const string HeroHeaderImageHorizontalAlignmentCodename = "hero__header_image_horizontal_alignment";
        public const string HeroHeaderImageVerticalAlignmentCodename = "hero__header_image_vertical_alignment";
        public const string SeoMetaDataMetaDescriptionCodename = "seo_meta_data__meta_description";
        public const string SeoMetaDataMetaImagesCodename = "seo_meta_data__meta_images";
        public const string SeoMetaDataMetaTitleCodename = "seo_meta_data__meta_title";
        public const string SeoMetaDataTwitterAccountCodename = "seo_meta_data__twitter_account";

        public string HeroHeader { get; set; }
        public IEnumerable<Asset> HeroHeaderImage { get; set; }
        public IEnumerable<MultipleChoiceOption> HeroHeaderImageHorizontalAlignment { get; set; }
        public IEnumerable<MultipleChoiceOption> HeroHeaderImageVerticalAlignment { get; set; }
        public string SeoMetaDataMetaDescription { get; set; }
        public IEnumerable<Asset> SeoMetaDataMetaImages { get; set; }
        public string SeoMetaDataMetaTitle { get; set; }
        public IEnumerable<MultipleChoiceOption> SeoMetaDataTwitterAccount { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}