// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace KenticoKontentBlog.Feature.Kontent.Models
{
    public partial class ImageCarousel
    {
        public const string Codename = "image_carousel";
        public const string CarouselImagesCodename = "carousel_images";
        public const string SortOrderCodename = "sort_order";
        public const string TitleCodename = "title";

        public IEnumerable<Asset> CarouselImages { get; set; }
        public IEnumerable<MultipleChoiceOption> SortOrder { get; set; }
        public ContentItemSystemAttributes System { get; set; }
        public string Title { get; set; }
    }
}