// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace KenticoKontentBlog.Feature.Kontent.Models
{
    public partial class Quote
    {
        public const string Codename = "quote";
        public const string AuthorCodename = "author";
        public const string QuotationCodename = "quotation";
        public const string SourceNameCodename = "source_name";
        public const string SourceUrlCodename = "source_url";

        public string Author { get; set; }
        public IRichTextContent Quotation { get; set; }
        public string SourceName { get; set; }
        public string SourceUrl { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}