// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System.Collections.Generic;

using Kentico.Kontent.Delivery.Abstractions;

namespace KenticoKontentBlog.Feature.Kontent.Models
{
    public partial class YoutubeVideo
    {
        public const string Codename = "youtube_video";
        public const string OptionsCodename = "options";
        public const string VideoIdCodename = "video_id";

        public IEnumerable<IMultipleChoiceOption> Options { get; set; }
        public IContentItemSystemAttributes System { get; set; }
        public string VideoId { get; set; }
    }
}